const $=s=>document.querySelector(s);let token=localStorage.getItem('urbisCitizenToken')||'',user=null,lastGps=null;
function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));}
function show(id,on=true){$(id).classList.toggle('hidden',!on)}
async function request(url,{method='GET',body,auth=true}={}){const headers={};if(body)headers['content-type']='application/json';if(auth&&token)headers.authorization='Bearer '+token;const r=await fetch(url,{method,headers,body:body?JSON.stringify(body):undefined});const j=await r.json();if(!r.ok)throw new Error(j.error||r.statusText);return j;}
async function login(){try{const j=await request('/v1/auth/login',{method:'POST',auth:false,body:{email:$('#email').value,password:$('#password').value}});token=j.accessToken;user=j.user;localStorage.setItem('urbisCitizenToken',token);await enter();}catch(e){alert('Falha no acesso: '+e.message)}}
async function enter(){try{user=await request('/v1/auth/me');show('#loginCard',false);show('#reportCard');show('#historyCard');show('#communityCard');$('#who').textContent=`${user.displayName} • ${user.email}`;await history();}catch{token='';localStorage.removeItem('urbisCitizenToken');show('#loginCard');show('#reportCard',false);show('#historyCard',false);show('#communityCard',false)}}
async function history(){const j=await request('/v1/me/occurrences');$('#history').innerHTML=j.records.length?j.records.map(o=>`<div class="history-item"><b>${esc(o.protocol)}</b> • ${esc(o.status)}<br>${esc(o.territory?.streetName??'Localização registrada')} • ${esc(o.categoryCode)}${o.status==='RESOLVED'?`<br><button class="secondary compact" data-eval="${o.id}">Avaliar serviço</button>`:''}</div>`).join(''):'Nenhuma ocorrência registrada.';document.querySelectorAll('[data-eval]').forEach(b=>b.onclick=()=>evaluate(b.dataset.eval));await community();}
async function evaluate(id){const v=prompt('Nota de 1 a 5 para o atendimento:','5');if(v==null)return;const c=prompt('Comentário opcional:','')??'';try{await request(`/v1/occurrences/${id}/evaluation`,{method:'POST',body:{rating:Number(v),comment:c}});alert('Avaliação registrada.');await community();}catch(e){alert('Avaliação: '+e.message)}}
async function community(){try{const [score,rank,notes,alerts]=await Promise.all([request('/v1/me/score'),request('/v1/rankings/current',{auth:false}),request('/v1/me/notifications'),request('/v1/alerts?'+(lastGps?`lat=${lastGps.latitude}&lon=${lastGps.longitude}`:''),{auth:false})]);const mine=rank.records.find(x=>x.userId===user?.id);$('#community').innerHTML=`<p><b>${score.totalPoints}</b> pontos validados • trimestre ${score.quarter}${mine?` • posição ${mine.position}`:''}</p><p><b>${alerts.count}</b> alertas ativos para a consulta atual.</p><p><b>${notes.count}</b> notificações registradas.</p>`;}catch(e){$('#community').textContent='Indicadores indisponíveis: '+e.message}}
$('#login').onclick=login;$('#logout').onclick=()=>{token='';user=null;localStorage.removeItem('urbisCitizenToken');show('#loginCard');show('#reportCard',false);show('#historyCard',false);show('#communityCard',false);show('#resultCard',false)};
$('#gps').onclick=()=>{const s=$('#status');if(!navigator.geolocation){s.textContent='GPS indisponível.';return}s.textContent='Obtendo localização…';navigator.geolocation.getCurrentPosition(p=>{lastGps={latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy,capturedAt:new Date().toISOString()};$('#lat').value=p.coords.latitude.toFixed(7);$('#lon').value=p.coords.longitude.toFixed(7);s.textContent=`GPS capturado • precisão indicada pelo dispositivo: ${Math.round(p.coords.accuracy)} m`;},e=>s.textContent='GPS: '+e.message,{enableHighAccuracy:true,timeout:12000})};
function fileBase64(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(file)})}
$('#send').onclick=async()=>{const s=$('#status');try{const latitude=Number($('#lat').value),longitude=Number($('#lon').value);if(!Number.isFinite(latitude)||!Number.isFinite(longitude))throw new Error('Capture o GPS ou informe coordenadas válidas.');s.textContent='Criando protocolo…';const c=await request('/v1/occurrences',{method:'POST',body:{categoryCode:$('#category').value,description:$('#description').value,latitude,longitude,gpsAccuracyM:lastGps?.accuracy??null,clientRequestId:crypto.randomUUID()}});let evidence=null;const file=$('#evidence').files[0];if(file){if(file.size>8*1024*1024)throw new Error('A evidência excede 8 MB neste alpha.');s.textContent='Enviando evidência e calculando integridade…';evidence=await request(`/v1/occurrences/${c.occurrence.id}/evidence`,{method:'POST',body:{filename:file.name,mediaType:file.type,dataBase64:await fileBase64(file),capturedAt:lastGps?.capturedAt??new Date(file.lastModified).toISOString(),latitude:lastGps?.latitude??latitude,longitude:lastGps?.longitude??longitude}})}const ici=evidence?.evidence?.ici;$('#result').innerHTML=`<div class="protocol">${esc(c.occurrence.protocol)}</div><p>${esc(c.occurrence.territory?.streetName??'Ponto fora do raio de associação automática')} • ${esc(c.occurrence.territory?.neighborhood??'')}</p>${ici?`<div class="ici"><b>ICI-URBIS: ${ici.score}/100 • ${ici.level}</b><br><small>Indicador de confiança de engenharia. Não constitui prova automática de veracidade ou autenticidade.</small></div>`:''}`;show('#resultCard');s.textContent='Ocorrência registrada.';await history();}catch(e){s.textContent='Erro: '+e.message}};
$('#newReport').onclick=()=>{show('#resultCard',false);$('#description').value='';$('#evidence').value='';$('#status').textContent='';};
if(token)enter();
