BEGIN;
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$ BEGIN
  CREATE TYPE occurrence_status AS ENUM ('OPEN','TRIAGE','DISPATCHED','IN_SERVICE','RESOLVED','REJECTED','DUPLICATE');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE evidence_status AS ENUM ('RECEIVED','GEO_VALIDATED','EVIDENCE_VALIDATED','CORROBORATED','AUTHORITY_VALIDATED','REJECTED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE source_kind AS ENUM ('CITIZEN_REPORT','FIELD_VALIDATION','OFFICIAL_SENSOR','OFFICIAL_DATASET','INTEGRATION');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE urgency_level AS ENUM ('LOW','NORMAL','HIGH','CRITICAL','EMERGENCY');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMIT;
