import React,{useEffect,useMemo,useRef,useState} from 'react';
import{createRoot}from'react-dom/client';
import mapboxgl from 'mapbox-gl';
import * as echarts from 'echarts';
import 'mapbox-gl/dist/mapbox-gl.css';
import './styles.css';

type Summary={occurrences?:number;occurrencesThisMonth?:number;byStatus?:Record<string,number|string>;byCategory?:Record<string,number|string>;slaCompliancePct?:number|null;meanResolutionHours?:number|null;meanCitizenRating?:number|null;overdueServiceOrders?:number|string};
type Occurrence={id:string;protocol:string;status:string;priority?:string;categoryCode?:string;category_code?:string;latitude?:number;longitude?:number;territory?:{neighborhood?:string};neighborhood?:string;description?:string};
const API=(import.meta.env.VITE_API_URL as string||'http://localhost:3000').replace(/\/$/,'');
const MAPBOX_TOKEN=String(import.meta.env.VITE_MAPBOX_TOKEN||'');

async function request(path:string,token:string,init:RequestInit={}){
  const headers=new Headers(init.headers);headers.set('content-type','application/json');if(token)headers.set('authorization',`Bearer ${token}`);
  const r=await fetch(`${API}${path}`,{...init,headers});const text=await r.text();let data:any={};try{data=text?JSON.parse(text):{};}catch{data={raw:text};}if(!r.ok)throw new Error(data?.message??data?.error??`HTTP ${r.status}`);return data;
}
function num(v:unknown){return Number(v??0)||0}

function App(){
  const [token,setToken]=useState(()=>sessionStorage.getItem('urbis-central-token')||'');
  const [email,setEmail]=useState('');const[password,setPassword]=useState('');const[message,setMessage]=useState('');
  const[summary,setSummary]=useState<Summary>({});const[occ,setOcc]=useState<Occurrence[]>([]);const[statusFilter,setStatusFilter]=useState('');const[categoryFilter,setCategoryFilter]=useState('');
  const mapNode=useRef<HTMLDivElement>(null);const chartNode=useRef<HTMLDivElement>(null);const mapRef=useRef<mapboxgl.Map|null>(null);
  const filtered=useMemo(()=>occ.filter(o=>(!statusFilter||o.status===statusFilter)&&(!categoryFilter||(o.categoryCode??o.category_code)===categoryFilter)),[occ,statusFilter,categoryFilter]);
  async function login(e:React.FormEvent){e.preventDefault();try{const j=await request('/v1/auth/login','',{method:'POST',body:JSON.stringify({email,password})});sessionStorage.setItem('urbis-central-token',j.accessToken);setToken(j.accessToken);setMessage(`Acesso: ${j.user?.displayName??j.user?.email}`);}catch(err:any){setMessage(err.message)}}
  async function refresh(){if(!token)return;try{const [s,o]=await Promise.all([request('/v1/dashboard/summary',token),request('/v1/occurrences?limit=1000',token)]);setSummary(s);setOcc(o.records??[]);setMessage('Dados atualizados.');}catch(err:any){setMessage(err.message)}}
  async function triage(id:string,decision:'PROCEDENT'|'IMPROCEDENT'|'DUPLICATE'){try{await request(`/v1/occurrences/${id}/triage`,token,{method:'POST',body:JSON.stringify({decision})});await refresh();}catch(err:any){setMessage(err.message)}}
  useEffect(()=>{if(token)void refresh()},[token]);
  useEffect(()=>{if(!chartNode.current)return;const chart=echarts.init(chartNode.current);const entries=Object.entries(summary.byStatus??{});chart.setOption({tooltip:{},xAxis:{type:'category',data:entries.map(([k])=>k)},yAxis:{type:'value'},series:[{type:'bar',data:entries.map(([,v])=>num(v))}]});const on=()=>chart.resize();addEventListener('resize',on);return()=>{removeEventListener('resize',on);chart.dispose()}},[summary]);
  useEffect(()=>{if(!MAPBOX_TOKEN||!mapNode.current)return;mapboxgl.accessToken=MAPBOX_TOKEN;if(!mapRef.current){mapRef.current=new mapboxgl.Map({container:mapNode.current,style:'mapbox://styles/mapbox/streets-v12',center:[-49.9,-6.07],zoom:11});mapRef.current.addControl(new mapboxgl.NavigationControl())}const m=mapRef.current;const render=()=>{const fc={type:'FeatureCollection',features:filtered.filter(o=>Number.isFinite(Number(o.longitude))&&Number.isFinite(Number(o.latitude))).map(o=>({type:'Feature',geometry:{type:'Point',coordinates:[Number(o.longitude),Number(o.latitude)]},properties:{id:o.id,protocol:o.protocol,status:o.status,category:o.categoryCode??o.category_code}}))} as GeoJSON.FeatureCollection;if(m.getSource('occ'))(m.getSource('occ') as mapboxgl.GeoJSONSource).setData(fc);else{m.addSource('occ',{type:'geojson',data:fc});m.addLayer({id:'occ-points',type:'circle',source:'occ',paint:{'circle-radius':6,'circle-stroke-width':1,'circle-stroke-color':'#fff','circle-color':['match',['get','status'],'RESOLVED','#259b58','IN_SERVICE','#287ed1','DISPATCHED','#cfad22','TRIAGE','#e88d24','OPEN','#d93838','#6f7a82']}})}};m.loaded()?render():m.once('load',render)},[filtered]);
  useEffect(()=>()=>mapRef.current?.remove(),[]);
  if(!token)return <main className="login"><section className="card"><h1>URBIS Central</h1><p>Central institucional de monitoramento georreferenciado.</p><form onSubmit={login}><label>E-mail<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required/></label><label>Senha<input value={password} onChange={e=>setPassword(e.target.value)} type="password" required/></label><button>Entrar</button></form><p aria-live="polite">{message}</p></section></main>;
  return <main><header><div><h1>URBIS Central</h1><p>GIS • triagem • despacho • indicadores</p></div><div><button onClick={()=>void refresh()}>Atualizar</button><button className="secondary" onClick={()=>{sessionStorage.removeItem('urbis-central-token');setToken('')}}>Sair</button></div></header>
    <section className="metrics"><article><b>{num(summary.occurrences)}</b><span>Total</span></article><article><b>{num(summary.occurrencesThisMonth)}</b><span>No mês</span></article><article><b>{summary.slaCompliancePct??'—'}%</b><span>Dentro do SLA</span></article><article><b>{summary.meanResolutionHours??'—'}</b><span>h resolução média</span></article><article><b>{summary.meanCitizenRating??'—'}</b><span>Satisfação</span></article><article><b>{num(summary.overdueServiceOrders)}</b><span>OS vencidas</span></article></section>
    <section className="grid"><article className="card"><h2>Mapa operacional</h2>{MAPBOX_TOKEN?<div ref={mapNode} className="map"/>:<div className="notice">Defina <code>VITE_MAPBOX_TOKEN</code> para o mapa Mapbox. A prova GIS local independente de provedor está em <code>apps/panel-gis-proof</code>.</div>}</article><article className="card"><h2>Ocorrências por status</h2><div ref={chartNode} className="chart"/></article></section>
    <section className="card"><div className="filters"><h2>Fila operacional</h2><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">Todos os status</option>{Object.keys(summary.byStatus??{}).map(x=><option key={x}>{x}</option>)}</select><select value={categoryFilter} onChange={e=>setCategoryFilter(e.target.value)}><option value="">Todas as categorias</option>{Object.keys(summary.byCategory??{}).map(x=><option key={x}>{x}</option>)}</select></div><div className="table"><table><thead><tr><th>Protocolo</th><th>Categoria</th><th>Status</th><th>Prioridade</th><th>Bairro</th><th>Ações</th></tr></thead><tbody>{filtered.map(o=><tr key={o.id}><td>{o.protocol}</td><td>{o.categoryCode??o.category_code}</td><td>{o.status}</td><td>{o.priority??'—'}</td><td>{o.territory?.neighborhood??o.neighborhood??'—'}</td><td>{['OPEN','TRIAGE'].includes(o.status)?<><button className="small" onClick={()=>void triage(o.id,'PROCEDENT')}>Procedente</button><button className="small secondary" onClick={()=>void triage(o.id,'IMPROCEDENT')}>Improcedente</button></>:null}</td></tr>)}</tbody></table></div></section><footer aria-live="polite">{message}</footer></main>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
