'use client';
import {useEffect,useRef,useState} from 'react';
import type {Map as LeafletMap,LayerGroup as LeafletLayerGroup} from 'leaflet';
const API=(process.env.NEXT_PUBLIC_URBIS_API_URL||'http://localhost:3000').replace(/\/$/,'');
type O={protocol:string;categoryCode?:string;category_code?:string;status:string;priority?:string;neighborhood?:string;approximateLocation?:{latitude:number;longitude:number;gridDegrees:number;notice?:string};createdAt?:string};
type S={occurrences?:number;byStatus?:Record<string,number|string>;meanResolutionHours?:number|null;meanCitizenRating?:number|null};
async function get(path:string){const r=await fetch(`${API}${path}`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
export default function PublicDashboard(){const [summary,setSummary]=useState<S>({}),[records,setRecords]=useState<O[]>([]),[protocol,setProtocol]=useState(''),[result,setResult]=useState<any>(null),[error,setError]=useState('');const node=useRef<HTMLDivElement>(null),map=useRef<LeafletMap|null>(null),layer=useRef<LeafletLayerGroup|null>(null);
 const refresh=async()=>{try{const[s,o]=await Promise.all([get('/public/summary'),get('/public/occurrences')]);setSummary(s);setRecords(o.records??[]);setError('')}catch(e:any){setError(e.message)}};
 useEffect(()=>{void refresh();const es=new EventSource(`${API}/public/stream`);es.addEventListener('occurrence.changed',()=>void refresh());es.addEventListener('alert.issued',()=>void refresh());return()=>es.close()},[]);
 useEffect(()=>{let cancelled=false;(async()=>{if(!node.current)return;const L=await import('leaflet');if(cancelled||!node.current)return;if(!map.current){map.current=L.map(node.current,{zoomControl:true}).setView([-6.07,-49.9],11);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors',maxZoom:19}).addTo(map.current);layer.current=L.layerGroup().addTo(map.current)}layer.current?.clearLayers();for(const o of records){const p=o.approximateLocation;if(!p)continue;L.circleMarker([p.latitude,p.longitude],{radius:6,weight:1,color:'#fff',fillColor:o.status==='RESOLVED'?'#259b58':o.status==='IN_SERVICE'?'#287ed1':o.status==='OPEN'?'#d93838':'#cf8b22',fillOpacity:.9}).bindPopup(`<b>${o.protocol}</b><br>${o.categoryCode??o.category_code??''}<br>${o.status}<br>${o.neighborhood??''}`).addTo(layer.current!)}})();return()=>{cancelled=true}},[records]);
 useEffect(()=>()=>{map.current?.remove();map.current=null;layer.current=null},[]);
 async function lookup(){try{setResult(await get(`/public/protocol/${encodeURIComponent(protocol.trim())}`));setError('')}catch(e:any){setResult(null);setError(e.message)}}
 const resolved=Number(summary.byStatus?.RESOLVED??0);return <main><header><h1>URBIS Transparência</h1><p>Mapa e indicadores agregados, sem identificação do cidadão e sem endereço exato.</p></header><section className="metrics"><article><b>{Number(summary.occurrences??0)}</b><span>Ocorrências</span></article><article><b>{resolved}</b><span>Resolvidas</span></article><article><b>{summary.meanResolutionHours??'—'}</b><span>h de resolução média</span></article><article><b>{summary.meanCitizenRating??'—'}</b><span>Satisfação média</span></article></section><section className="card"><h2>Mapa público</h2><p className="privacy">Os marcadores representam localização generalizada. Não correspondem ao ponto exato enviado pelo cidadão.</p><div ref={node} className="map" aria-label="Mapa público de ocorrências URBIS"/></section><section className="grid"><article className="card"><h2>Ocorrências recentes</h2><div className="list">{records.slice(0,100).map(o=><div key={o.protocol}><b>{o.protocol}</b><span>{o.categoryCode??o.category_code} • {o.status} • {o.neighborhood??'bairro não identificado'}</span></div>)}</div></article><article className="card"><h2>Consultar protocolo</h2><div className="search"><input value={protocol} onChange={e=>setProtocol(e.target.value)} placeholder="URB-AAAAMMDD-0000001"/><button onClick={()=>void lookup()}>Consultar</button></div>{result?<pre>{JSON.stringify(result,null,2)}</pre>:null}{error?<p className="error">{error}</p>:null}</article></section><footer>URBIS — Uma cidade melhor começa com você.</footer></main>}
