import { Controller, Get, Header, Res, UseGuards } from '@nestjs/common';
import type { Response } from 'express';
import { AuthGuard } from '../auth/auth.guard';import { RolesGuard } from '../auth/roles.guard';import { Roles } from '../auth/auth.decorators';import { DatabaseService } from '../database/database.service';
function csvEsc(v:any){const s=String(v??'');return /[",\n\r]/.test(s)?`"${s.replaceAll('"','""')}"`:s}
function pdfEsc(s:any){return String(s??'').replaceAll('\\','\\\\').replaceAll('(','\\(').replaceAll(')','\\)').replace(/[\r\n]+/g,' ')}
function pdf(lines:string[]){const c=['BT','/F1 12 Tf','50 800 Td','(URBIS - Relatorio de Ocorrencias) Tj'];for(const l of lines.slice(0,45))c.push('0 -16 Td',`(${pdfEsc(l).slice(0,180)}) Tj`);c.push('ET');const st=c.join('\n'),o:any[]=[];o[1]='<< /Type /Catalog /Pages 2 0 R >>';o[2]='<< /Type /Pages /Kids [3 0 R] /Count 1 >>';o[3]='<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>';o[4]=`<< /Length ${Buffer.byteLength(st)} >>\nstream\n${st}\nendstream`;o[5]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';let out='%PDF-1.4\n';const off=[0];for(let i=1;i<=5;i++){off[i]=Buffer.byteLength(out);out+=`${i} 0 obj\n${o[i]}\nendobj\n`}const x=Buffer.byteLength(out);out+='xref\n0 6\n0000000000 65535 f \n';for(let i=1;i<=5;i++)out+=`${String(off[i]).padStart(10,'0')} 00000 n \n`;out+=`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${x}\n%%EOF\n`;return Buffer.from(out,'binary')}
const crcT=(()=>{const t:number[]=[];for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;t[n]=c>>>0}return t})();function crc32(b:Buffer){let c=0xffffffff;for(const x of b)c=crcT[(c^x)&255]^(c>>>8);return(c^0xffffffff)>>>0}
function zip(entries:[string,string][]) {const locals:Buffer[]=[],centrals:Buffer[]=[];let offset=0;for(const [name,text]of entries){const data=Buffer.from(text),n=Buffer.from(name),crc=crc32(data),lh=Buffer.alloc(30);lh.writeUInt32LE(0x04034b50,0);lh.writeUInt16LE(20,4);lh.writeUInt32LE(crc,14);lh.writeUInt32LE(data.length,18);lh.writeUInt32LE(data.length,22);lh.writeUInt16LE(n.length,26);locals.push(lh,n,data);const ch=Buffer.alloc(46);ch.writeUInt32LE(0x02014b50,0);ch.writeUInt16LE(20,4);ch.writeUInt16LE(20,6);ch.writeUInt32LE(crc,16);ch.writeUInt32LE(data.length,20);ch.writeUInt32LE(data.length,24);ch.writeUInt16LE(n.length,28);ch.writeUInt32LE(offset,42);centrals.push(ch,n);offset+=lh.length+n.length+data.length}const central=Buffer.concat(centrals),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50,0);end.writeUInt16LE(entries.length,8);end.writeUInt16LE(entries.length,10);end.writeUInt32LE(central.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...locals,central,end])}
function xe(s:any){return String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
function xlsx(rows:any[]){const data=[['Protocolo','Categoria','Status','Prioridade','Bairro','Criada em','Resolvida em'],...rows.map(r=>[r.protocol,r.category_code,r.status,r.priority,r.neighborhood,r.created_at,r.resolved_at])],letters='ABCDEFG';const sr=data.map((r,i)=>`<row r="${i+1}">${r.map((v,j)=>`<c r="${letters[j]}${i+1}" t="inlineStr"><is><t>${xe(v)}</t></is></c>`).join('')}</row>`).join('');return zip([['[Content_Types].xml','<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>'],['_rels/.rels','<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'],['xl/workbook.xml','<?xml version="1.0"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Ocorrencias" sheetId="1" r:id="rId1"/></sheets></workbook>'],['xl/_rels/workbook.xml.rels','<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>'],['xl/worksheets/sheet1.xml',`<?xml version="1.0"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${sr}</sheetData></worksheet>`]])}
@Controller('v1/reports')@UseGuards(AuthGuard,RolesGuard)@Roles('OPERATOR','MANAGER','ADMIN')
export class ReportsController{constructor(private readonly db:DatabaseService){}private async rows(){const q=await this.db.query(`SELECT o.protocol,c.code category_code,o.status,o.priority,o.territory_snapshot->>'neighborhood' neighborhood,o.created_at,o.resolved_at FROM occurrences o JOIN categories c ON c.id=o.category_id ORDER BY o.created_at DESC LIMIT 10000`);return q.rows}
@Get('occurrences.csv')async csv(@Res()res:Response){const rows=await this.rows(),b=Buffer.from('\uFEFF'+[['protocol','category','status','priority','neighborhood','created_at','resolved_at'].join(','),...rows.map((r:any)=>[r.protocol,r.category_code,r.status,r.priority,r.neighborhood,r.created_at,r.resolved_at].map(csvEsc).join(','))].join('\r\n'));res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition','attachment; filename="urbis-occurrences.csv"');res.send(b)}
@Get('occurrences.pdf')async pdf(@Res()res:Response){const rows=await this.rows(),b=pdf(rows.map((r:any)=>`${r.protocol} | ${r.category_code} | ${r.status} | ${r.neighborhood??''}`));res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition','attachment; filename="urbis-occurrences.pdf"');res.send(b)}
@Get('occurrences.xlsx')async xlsx(@Res()res:Response){const b=xlsx(await this.rows());res.setHeader('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');res.setHeader('Content-Disposition','attachment; filename="urbis-occurrences.xlsx"');res.send(b)}}
