import test from 'node:test';import assert from 'node:assert/strict';
import { activeAlerts, createEvaluation, createValidatedScore, dashboardSummary, inferPriority, publicOccurrence, rankingForQuarter, validateFieldTransition, warrantyMatches } from '../core/business-core.mjs';

const occurrence={id:'o1',protocol:'URB-20260907-0000001',reporterUserId:'u1',categoryCode:'PAVEMENT',status:'RESOLVED',latitude:-6.07,longitude:-49.90,territory:{neighborhood:'Centro',streetName:'Rua A',zone:'Urbana'},createdAt:'2026-07-01T10:00:00Z',resolvedAt:'2026-07-01T12:00:00Z'};

test('prioridade automática e manual',()=>{assert.equal(inferPriority({categoryCode:'PAVEMENT'}).priority,'MEDIUM');assert.equal(inferPriority({categoryCode:'PAVEMENT',manualPriority:'CRITICAL'}).source,'MANUAL');});
test('avaliação somente após resolução e pelo autor',()=>{const e=createEvaluation({occurrence,userId:'u1',rating:5});assert.equal(e.rating,5);assert.throws(()=>createEvaluation({occurrence:{...occurrence,status:'OPEN'},userId:'u1',rating:5}),/not_resolved/);});
test('pontuação exige validação humana e base 1 a 4',()=>{const s=createValidatedScore({occurrence,userId:'u1',basePoints:4,bonusPoints:2,validatedBy:'manager'});assert.equal(s.points,6);assert.throws(()=>createValidatedScore({occurrence,userId:'u1',basePoints:5,validatedBy:'manager'}),/out_of_range/);});
test('ranking trimestral agrega pontos',()=>{const r=rankingForQuarter([{userId:'u1',points:3,createdAt:'2026-07-10T00:00:00Z'},{userId:'u1',points:2,createdAt:'2026-08-10T00:00:00Z'}],[{id:'u1',displayName:'Charles'}],{quarter:'2026-Q3'});assert.equal(r[0].points,5);assert.equal(r[0].position,1);});
test('alerta geográfico filtra ponto dentro de polígono',()=>{const a={id:'a1',issuedAt:'2026-09-01T00:00:00Z',expiresAt:'2026-10-01T00:00:00Z',area:{type:'Polygon',coordinates:[[[-50,-7],[-49,-7],[-49,-6],[-50,-6],[-50,-7]]]}};assert.equal(activeAlerts([a],{lat:-6.5,lon:-49.5,now:'2026-09-07T00:00:00Z'}).length,1);assert.equal(activeAlerts([a],{lat:-5,lon:-49.5,now:'2026-09-07T00:00:00Z'}).length,0);});
test('publicação remove endereço, autor e ponto exato',()=>{const p=publicOccurrence({...occurrence,addressText:'Rua A 10',reporter:{name:'X'}});assert.equal(p.neighborhood,'Centro');assert.equal('addressText' in p,false);assert.equal('reporter' in p,false);assert.equal(p.approximateLocation.gridDegrees,0.005);assert.match(p.approximateLocation.notice,/generalizada/);});
test('geofence bloqueia conclusão distante',()=>{const w={id:'w1',occurrenceId:'o1'};assert.throws(()=>validateFieldTransition({workOrder:w,occurrence,status:'COMPLETED',latitude:-6.2,longitude:-49.9}),/outside_work_order_geofence/);const ok=validateFieldTransition({workOrder:w,occurrence,status:'COMPLETED',latitude:-6.0701,longitude:-49.9001});assert.ok(ok.distanceM<250);});
test('garantia cruza rua/bairro sem inventar contrato',()=>{const c={id:'c1',contractNumber:'X',streetName:'Rua A',neighborhood:'Centro',warrantyUntil:'2027-01-01'};assert.equal(warrantyMatches([c],occurrence,{now:'2026-09-07'}).length,1);assert.equal(warrantyMatches([{...c,warrantyUntil:'2020-01-01'}],occurrence,{now:'2026-09-07'}).length,0);});
test('dashboard calcula resolução e satisfação',()=>{const d=dashboardSummary({occurrences:[occurrence],workOrders:[{completedAt:'2026-07-01T11:00:00Z',slaDueAt:'2026-07-01T13:00:00Z'}],evaluations:[{rating:4}],users:[{id:'u1'}],scores:[{points:3}]});assert.equal(d.meanResolutionHours,2);assert.equal(d.slaCompliancePct,100);assert.equal(d.meanCitizenRating,4);});
