import zlib from 'node:zlib';

function escapeCsv(v){const s=String(v??'');return /[",\n\r]/.test(s)?`"${s.replaceAll('"','""')}"`:s;}
export function occurrencesCsv(records=[]){const cols=['protocol','categoryCode','status','priority','neighborhood','createdAt','resolvedAt'];const rows=[cols.join(',')];for(const o of records){const n=o.territory?.neighborhood??o.territorySnapshot?.neighborhood??'';rows.push([o.protocol,o.categoryCode,o.status,o.priority??'',n,o.createdAt,o.resolvedAt??''].map(escapeCsv).join(','));}return Buffer.from('\uFEFF'+rows.join('\r\n'),'utf8');}

function pdfEscape(s){return String(s??'').replaceAll('\\','\\\\').replaceAll('(','\\(').replaceAll(')','\\)').replace(/[\r\n]+/g,' ');}
export function simplePdfReport({title='URBIS - Relatório',lines=[]}={}){
  const content=['BT','/F1 12 Tf','50 800 Td',`(${pdfEscape(title)}) Tj`];let y=0;for(const line of lines.slice(0,45)){y-=16;content.push(`0 ${y===-16?-16:-16} Td`,`(${pdfEscape(line).slice(0,180)}) Tj`);}content.push('ET');const stream=content.join('\n');
  const objs=[];objs[1]='<< /Type /Catalog /Pages 2 0 R >>';objs[2]='<< /Type /Pages /Kids [3 0 R] /Count 1 >>';objs[3]='<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>';objs[4]=`<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`;objs[5]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';
  let out='%PDF-1.4\n';const offsets=[0];for(let i=1;i<=5;i++){offsets[i]=Buffer.byteLength(out);out+=`${i} 0 obj\n${objs[i]}\nendobj\n`;}const xref=Buffer.byteLength(out);out+='xref\n0 6\n0000000000 65535 f \n';for(let i=1;i<=5;i++)out+=`${String(offsets[i]).padStart(10,'0')} 00000 n \n`;out+=`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;return Buffer.from(out,'binary');
}

// Minimal ZIP writer (stored entries) for a valid XLSX without external dependencies.
const crcTable=(()=>{const t=[];for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;t[n]=c>>>0;}return t;})();
function crc32(buf){let c=0xffffffff;for(const b of buf)c=crcTable[(c^b)&0xff]^(c>>>8);return (c^0xffffffff)>>>0;}
function zipStored(entries){const locals=[],centrals=[];let offset=0;for(const [name,dataRaw] of entries){const data=Buffer.isBuffer(dataRaw)?dataRaw:Buffer.from(dataRaw);const n=Buffer.from(name);const crc=crc32(data);const lh=Buffer.alloc(30);lh.writeUInt32LE(0x04034b50,0);lh.writeUInt16LE(20,4);lh.writeUInt16LE(0,6);lh.writeUInt16LE(0,8);lh.writeUInt16LE(0,10);lh.writeUInt16LE(0,12);lh.writeUInt32LE(crc,14);lh.writeUInt32LE(data.length,18);lh.writeUInt32LE(data.length,22);lh.writeUInt16LE(n.length,26);lh.writeUInt16LE(0,28);locals.push(lh,n,data);const ch=Buffer.alloc(46);ch.writeUInt32LE(0x02014b50,0);ch.writeUInt16LE(20,4);ch.writeUInt16LE(20,6);ch.writeUInt16LE(0,8);ch.writeUInt16LE(0,10);ch.writeUInt16LE(0,12);ch.writeUInt16LE(0,14);ch.writeUInt32LE(crc,16);ch.writeUInt32LE(data.length,20);ch.writeUInt32LE(data.length,24);ch.writeUInt16LE(n.length,28);ch.writeUInt16LE(0,30);ch.writeUInt16LE(0,32);ch.writeUInt16LE(0,34);ch.writeUInt16LE(0,36);ch.writeUInt32LE(0,38);ch.writeUInt32LE(offset,42);centrals.push(ch,n);offset+=lh.length+n.length+data.length;}const central=Buffer.concat(centrals);const end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50,0);end.writeUInt16LE(0,4);end.writeUInt16LE(0,6);end.writeUInt16LE(entries.length,8);end.writeUInt16LE(entries.length,10);end.writeUInt32LE(central.length,12);end.writeUInt32LE(offset,16);end.writeUInt16LE(0,20);return Buffer.concat([...locals,central,end]);}
function xmlEscape(s){return String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');}
function cell(v,ref){return `<c r="${ref}" t="inlineStr"><is><t>${xmlEscape(v)}</t></is></c>`;}
export function occurrencesXlsx(records=[]){const headers=['Protocolo','Categoria','Status','Prioridade','Bairro','Criada em','Resolvida em'];const rows=[headers,...records.map(o=>[o.protocol,o.categoryCode,o.status,o.priority??'',o.territory?.neighborhood??o.territorySnapshot?.neighborhood??'',o.createdAt,o.resolvedAt??''])];const letters='ABCDEFG';const sheetRows=rows.map((r,i)=>`<row r="${i+1}">${r.map((v,j)=>cell(v,`${letters[j]}${i+1}`)).join('')}</row>`).join('');const sheet=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${sheetRows}</sheetData></worksheet>`;const entries=[
['[Content_Types].xml','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>'],
['_rels/.rels','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'],
['xl/workbook.xml','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Ocorrencias" sheetId="1" r:id="rId1"/></sheets></workbook>'],
['xl/_rels/workbook.xml.rels','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>'],
['xl/worksheets/sheet1.xml',sheet]
];return zipStored(entries);}
