const STATUS={OPEN:'#df3434',TRIAGE:'#ef9026',DISPATCHED:'#d5b82d',IN_SERVICE:'#2d80db',RESOLVED:'#25a65a',REJECTED:'#818b92',DUPLICATE:'#818b92'};
let streets=null,records=[];
function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));}
async function json(url){const r=await fetch(url);const j=await r.json();if(!r.ok)throw new Error(j.error||r.statusText);return j;}
function bounds(fs){let b={minx:180,miny:90,maxx:-180,maxy:-90};for(const f of fs??[])for(const l of f.geometry?.coordinates??[])for(const [x,y] of l){b.minx=Math.min(b.minx,x);b.miny=Math.min(b.miny,y);b.maxx=Math.max(b.maxx,x);b.maxy=Math.max(b.maxy,y)}return b;}
function draw(){if(!streets)return;const c=document.querySelector('#publicMap'),d=devicePixelRatio||1,r=c.getBoundingClientRect();c.width=Math.max(1,Math.round(r.width*d));c.height=Math.max(1,Math.round(r.height*d));const x=c.getContext('2d');x.setTransform(d,0,0,d,0,0);x.clearRect(0,0,r.width,r.height);const b=bounds(streets.features),pad=12,s=Math.min((r.width-pad*2)/(b.maxx-b.minx),(r.height-pad*2)/(b.maxy-b.miny)),ox=(r.width-(b.maxx-b.minx)*s)/2,oy=(r.height-(b.maxy-b.miny)*s)/2,to=(lon,lat)=>[ox+(lon-b.minx)*s,r.height-(oy+(lat-b.miny)*s)];x.strokeStyle='#a7bdc9';x.lineWidth=.55;x.globalAlpha=.55;for(const f of streets.features)for(const line of f.geometry.coordinates){x.beginPath();line.forEach(([lon,lat],i)=>{const p=to(lon,lat);i?x.lineTo(...p):x.moveTo(...p)});x.stroke()}x.globalAlpha=1;for(const o of records){const p=o.approximateLocation;if(!p)continue;const q=to(Number(p.longitude),Number(p.latitude));x.beginPath();x.arc(q[0],q[1],5,0,Math.PI*2);x.fillStyle=STATUS[o.status]||'#283e4a';x.fill();x.strokeStyle='#fff';x.lineWidth=1.5;x.stroke();}}
async function refresh(){const [s,o]=await Promise.all([json('/public/summary'),json('/public/occurrences')]);records=o.records??[];document.querySelector('#metrics').innerHTML=`<div class="metric"><small>Total</small><br><b>${s.occurrences??0}</b></div><div class="metric"><small>Resolvidas</small><br><b>${s.byStatus?.RESOLVED??0}</b></div><div class="metric"><small>Tempo médio</small><br><b>${s.meanResolutionHours??'—'}</b><small> h</small></div><div class="metric"><small>Satisfação</small><br><b>${s.meanCitizenRating??'—'}</b></div>`;document.querySelector('#list').innerHTML=records.length?records.slice().reverse().map(x=>`<div class="item"><b>${esc(x.protocol)}</b> • ${esc(x.categoryCode??x.category_code)} • ${esc(x.status)}<br>${esc(x.neighborhood??'Bairro não identificado')} • prioridade ${esc(x.priority??'—')}</div>`).join(''):'Sem ocorrências públicas.';draw();}
document.querySelector('#find').onclick=async()=>{try{document.querySelector('#result').textContent=JSON.stringify(await json('/public/protocol/'+encodeURIComponent(document.querySelector('#protocol').value.trim())),null,2)}catch(e){document.querySelector('#result').textContent=e.message}};
streets=await json('/data/streets.geojson');const es=new EventSource('/public/stream');es.addEventListener('occurrence.changed',refresh);es.addEventListener('alert.issued',refresh);addEventListener('resize',draw);refresh();
