const $=s=>document.querySelector(s);let token='',gps=null;
async function req(url,{method='GET',body}={}){const h={authorization:'Bearer '+token};if(body)h['content-type']='application/json';const r=await fetch(url,{method,headers:h,body:body?JSON.stringify(body):undefined});const j=await r.json();if(!r.ok)throw new Error(j.error||r.statusText);return j;}
$('#go').onclick=async()=>{try{const r=await fetch('/v1/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:$('#email').value,password:$('#password').value})});const j=await r.json();if(!r.ok)throw new Error(j.error);token=j.accessToken;$('#login').classList.add('hidden');$('#work').classList.remove('hidden');await load();}catch(e){alert(e.message)}};
$('#gps').onclick=()=>navigator.geolocation?.getCurrentPosition(p=>{gps={latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy};$('#gpsState').textContent=`GPS: ${gps.latitude.toFixed(6)}, ${gps.longitude.toFixed(6)} • precisão ${Math.round(gps.accuracy)} m`;},e=>alert(e.message),{enableHighAccuracy:true,timeout:12000});
function fileBase64(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(file)})}
async function uploadEvidence(orderId,occurrenceId,purpose){const input=document.querySelector(`[data-file=\"${orderId}\"]`),file=input?.files?.[0];if(!file){alert('Selecione uma foto ou vídeo.');return;}try{await req(`/v1/occurrences/${occurrenceId}/evidence`,{method:'POST',body:{filename:file.name,mediaType:file.type,dataBase64:await fileBase64(file),purpose,capturedAt:new Date().toISOString(),latitude:gps?.latitude,longitude:gps?.longitude}});alert(`Evidência ${purpose} enviada.`);}catch(e){alert(e.message)}}
async function route(id){if(!gps){alert('Capture o GPS antes de solicitar a rota.');return;}try{const j=await req(`/v1/field/work-orders/${id}/route?lat=${gps.latitude}&lon=${gps.longitude}`);alert(`${j.provider}: ${Math.round(j.distanceM)} m${j.durationS?` • ${Math.round(j.durationS/60)} min`:''}${j.notice?`\n${j.notice}`:''}`);}catch(e){alert(e.message)}}
async function update(id,status){if(['ARRIVED','IN_PROGRESS','COMPLETED'].includes(status)&&!gps){alert('Capture o GPS antes desta etapa.');return;}try{await req(`/v1/field/work-orders/${id}/status`,{method:'POST',body:{status,latitude:gps?.latitude,longitude:gps?.longitude,result:status==='COMPLETED'?{note:'Conclusão registrada no app de campo de prova'}:null}});await load();}catch(e){alert(e.message)}}
async function load(){const j=await req('/v1/field/work-orders');$('#orders').innerHTML=j.records.length?j.records.map(w=>`<article class="order"><b>OS ${w.id.slice(0,8)}</b><div class="muted">Ocorrência ${w.occurrenceId.slice(0,8)} • ${w.status}</div><input data-file="${w.id}" type="file" accept="image/jpeg,image/png,image/webp,video/mp4"><div class="actions"><button data-route="${w.id}">Rota</button><button data-up="BEFORE" data-id="${w.id}" data-occ="${w.occurrenceId}">Foto antes</button><button data-up="AFTER" data-id="${w.id}" data-occ="${w.occurrenceId}">Foto depois</button><button data-id="${w.id}" data-s="EN_ROUTE">Em rota</button><button data-id="${w.id}" data-s="ARRIVED">Cheguei</button><button data-id="${w.id}" data-s="IN_PROGRESS">Iniciar</button><button data-id="${w.id}" data-s="COMPLETED">Concluir</button></div></article>`).join(''):'Nenhuma OS atribuída.';document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>route(b.dataset.route));document.querySelectorAll('[data-s]').forEach(b=>b.onclick=()=>update(b.dataset.id,b.dataset.s));document.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>uploadEvidence(b.dataset.id,b.dataset.occ,b.dataset.up));}
$('#refresh').onclick=load;
