const canvas=document.querySelector('#map'),ctx=canvas.getContext('2d');
let accessToken=localStorage.getItem('urbisOperatorToken')||'';let currentUser=null;
const $=s=>document.querySelector(s);
const els={authEmail:$('#authEmail'),authPassword:$('#authPassword'),authState:$('#authState'),zone:$('#zone'),bairro:$('#bairro'),mode:$('#mode'),details:$('#details'),lat:$('#lat'),lon:$('#lon'),category:$('#category'),description:$('#description'),formState:$('#formState'),pickBanner:$('#pickBanner'),wsState:$('#wsState')};
const STATUS_COLORS={OPEN:'#e43b3b',TRIAGE:'#f29b32',DISPATCHED:'#e5c445',IN_SERVICE:'#2f8de4',RESOLVED:'#2dbd69',REJECTED:'#7f8b94',DUPLICATE:'#7f8b94'};
async function authFetch(url,options={}){const headers={...(options.headers||{})};if(accessToken)headers.authorization='Bearer '+accessToken;const r=await fetch(url,{...options,headers});if(r.status===401){accessToken='';localStorage.removeItem('urbisOperatorToken');els.authState.textContent='Sessão expirada. Entre novamente.';}return r;}
async function login(){try{const r=await fetch('/v1/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:els.authEmail.value,password:els.authPassword.value})});const j=await r.json();if(!r.ok)throw new Error(j.error||'login_failed');accessToken=j.accessToken;currentUser=j.user;localStorage.setItem('urbisOperatorToken',accessToken);els.authState.textContent=`${j.user.displayName} • ${j.user.roles.join(', ')}`;await refreshOperations();connectWs();}catch(e){els.authState.textContent='Acesso negado: '+e.message;}}
$('#authLogin').onclick=login;
const [geo,meta]=await Promise.all([fetch('/data/streets.geojson').then(r=>r.json()),fetch('/v1/territory/stats').then(r=>r.json())]);
$('#mSegments').textContent=(meta.operational_feature_count??meta.segment_count??geo.features.length).toLocaleString('pt-BR');$('#mNeighborhoods').textContent=meta.unique_neighborhoods??meta.neighborhood_count??'—';$('#mQuarantine').textContent=meta.quarantine_feature_count??'—';
const uniq=k=>[...new Set(geo.features.map(f=>f.properties[k]).filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),'pt-BR'));for(const z of uniq('Zona'))els.zone.add(new Option(z,z));for(const b of uniq('bairro'))els.bairro.add(new Option(b,b));
let view={...bounds(geo.features)},selectedStreet=null,selectedOccurrence=null,occurrences=[],workOrders=[],pickMode=false,markerPixels=[];
function bounds(fs){let b={minx:180,miny:90,maxx:-180,maxy:-90};for(const f of fs)for(const l of f.geometry.coordinates)for(const [x,y] of l){b.minx=Math.min(b.minx,x);b.miny=Math.min(b.miny,y);b.maxx=Math.max(b.maxx,x);b.maxy=Math.max(b.maxy,y)}return b}
function active(){return geo.features.filter(f=>(!els.zone.value||f.properties.Zona===els.zone.value)&&(!els.bairro.value||f.properties.bairro===els.bairro.value));}
function size(){const d=devicePixelRatio||1,r=canvas.getBoundingClientRect();canvas.width=Math.max(1,Math.round(r.width*d));canvas.height=Math.max(1,Math.round(r.height*d));ctx.setTransform(d,0,0,d,0,0);return r}
function projector(r){const pad=20,w=r.width-pad*2,h=r.height-pad*2,dx=view.maxx-view.minx,dy=view.maxy-view.miny,s=Math.min(w/dx,h/dy),ox=(r.width-dx*s)/2,oy=(r.height-dy*s)/2;return {to:(x,y)=>[ox+(x-view.minx)*s,r.height-(oy+(y-view.miny)*s)],from:(px,py)=>[(px-ox)/s+view.minx,(r.height-py-oy)/s+view.miny]}}
function lineColor(v,mode){if(mode==='default')return '#2b7897';const s=String(v??'');return ({'0':'#6f7f89','1':'#17a56b','2':'#d59b2c','3':'#2c8bd4','4':'#d45050'})[s]||'#5a6470'}
function draw(){const r=size(),pr=projector(r),fs=active();ctx.clearRect(0,0,r.width,r.height);ctx.lineCap='round';for(const f of fs){ctx.strokeStyle=lineColor(f.properties[els.mode.value],els.mode.value);ctx.lineWidth=selectedStreet===f?3:0.8;ctx.globalAlpha=selectedStreet===f?1:.62;for(const line of f.geometry.coordinates){if(!line.length)continue;ctx.beginPath();line.forEach(([x,y],i)=>{const p=pr.to(x,y);i?ctx.lineTo(...p):ctx.moveTo(...p)});ctx.stroke()}}ctx.globalAlpha=1;markerPixels=[];for(const o of occurrences){const [x,y]=pr.to(Number(o.longitude),Number(o.latitude));markerPixels.push({x,y,o});ctx.beginPath();ctx.arc(x,y,selectedOccurrence?.id===o.id?8:6,0,Math.PI*2);ctx.fillStyle=STATUS_COLORS[o.status]||'#fff';ctx.fill();ctx.lineWidth=2;ctx.strokeStyle=selectedOccurrence?.id===o.id?'#fff':'#071824';ctx.stroke();}}
function fit(){const fs=active();if(fs.length)view={...bounds(fs)};draw()}
function distPointSeg(px,py,x1,y1,x2,y2){const vx=x2-x1,vy=y2-y1,wx=px-x1,wy=py-y1,vv=vx*vx+vy*vy;let t=vv?(wx*vx+wy*vy)/vv:0;t=Math.max(0,Math.min(1,t));return Math.hypot(px-(x1+t*vx),py-(y1+t*vy))}
function htmlSafe(v){return String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function showStreet(f){selectedStreet=f;selectedOccurrence=null;const p=f.properties;els.details.innerHTML=`<b>${htmlSafe(p.nom_novo||'Sem nome')}</b><dl><dt>CEP</dt><dd>${htmlSafe(p.cep)}</dd><dt>Bairro / Zona</dt><dd>${htmlSafe(p.bairro)} / ${htmlSafe(p.Zona)}</dd><dt>Entre ruas</dt><dd>${htmlSafe(p.entre_ruas)}</dd><dt>Pavimentação</dt><dd>${htmlSafe(p.pavimentac)}</dd><dt>Drenagem</dt><dd>${htmlSafe(p.drenagem)}</dd><dt>Iluminação</dt><dd>${htmlSafe(p.iluminacao)}</dd><dt>Setor fiscal</dt><dd>${htmlSafe(p.setor_fisc)}</dd></dl>`;draw();}
function showOccurrence(o){selectedOccurrence=o;selectedStreet=null;const wo=workOrders.find(w=>w.occurrenceId===o.id);let actions='';if(!['RESOLVED','REJECTED','DUPLICATE','DISPATCHED','IN_SERVICE'].includes(o.status))actions=`<div class="actions"><button data-triage="PROCEDENT">Procedente</button><button data-triage="IMPROCEDENT">Improcedente</button><button data-triage="DUPLICATE">Duplicada</button></div>`;let wa='';if(wo&&!['COMPLETED','CANCELLED'].includes(wo.status))wa=`<div class="work-actions"><button data-wo="IN_PROGRESS">Iniciar atendimento</button><button data-wo="COMPLETED">Concluir</button></div>`;els.details.innerHTML=`<b>${htmlSafe(o.protocol)}</b> <span class="status-pill">${htmlSafe(o.status)}</span><dl><dt>Categoria</dt><dd>${htmlSafe(o.categoryCode)}</dd><dt>Descrição</dt><dd>${htmlSafe(o.description||'—')}</dd><dt>Logradouro inferido</dt><dd>${htmlSafe(o.territory?.streetName)} • ${htmlSafe(o.territory?.neighborhood)}</dd><dt>CEP</dt><dd>${htmlSafe(o.cep)}</dd><dt>Distância à malha</dt><dd>${o.territory?.distanceM!=null?Number(o.territory.distanceM).toFixed(2)+' m':'—'}</dd><dt>Duplicidade sugerida</dt><dd>${o.duplicateSuspected?'SIM':'não'}</dd>${wo?`<dt>Ordem de serviço</dt><dd>${htmlSafe(wo.id.slice(0,8))} • ${htmlSafe(wo.status)} • ${htmlSafe(wo.responsibleOrgCode)}</dd>`:''}</dl>${actions}${wa}`;els.details.querySelectorAll('[data-triage]').forEach(b=>b.onclick=()=>triage(o.id,b.dataset.triage));els.details.querySelectorAll('[data-wo]').forEach(b=>b.onclick=()=>advance(wo.id,b.dataset.wo));draw();}
canvas.addEventListener('click',e=>{const r=canvas.getBoundingClientRect(),px=e.clientX-r.left,py=e.clientY-r.top,pr=projector(r);if(pickMode){const [lon,lat]=pr.from(px,py);els.lon.value=lon.toFixed(7);els.lat.value=lat.toFixed(7);pickMode=false;els.pickBanner.classList.add('hidden');els.formState.textContent='Coordenadas capturadas do mapa. Registre a ocorrência.';return;}let m=markerPixels.map(x=>({...x,d:Math.hypot(px-x.x,py-x.y)})).sort((a,b)=>a.d-b.d)[0];if(m&&m.d<12)return showOccurrence(m.o);let best={d:Infinity,f:null};for(const f of active())for(const line of f.geometry.coordinates)for(let i=1;i<line.length;i++){const a=pr.to(...line[i-1]),b=pr.to(...line[i]),d=distPointSeg(px,py,...a,...b);if(d<best.d)best={d,f}}if(best.d<12)showStreet(best.f);});
async function refreshOperations(){const [o,w,s]=await Promise.all([authFetch('/v1/occurrences').then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error||r.statusText);return j}),authFetch('/v1/work-orders').then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error||r.statusText);return j}),authFetch('/v1/dashboard/summary').then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error||r.statusText);return j})]);occurrences=o.records??[];workOrders=w.records??[];$('#mOccurrences').textContent=s.occurrences??0;$('#mOpen').textContent=(s.byStatus?.OPEN??0)+(s.byStatus?.TRIAGE??0);$('#mDispatched').textContent=s.byStatus?.DISPATCHED??0;$('#mService').textContent=s.byStatus?.IN_SERVICE??0;$('#mResolved').textContent=s.byStatus?.RESOLVED??0;$('#mSla').textContent=s.slaCompliancePct==null?'—':s.slaCompliancePct+'%';$('#mRating').textContent=s.meanCitizenRating??'—';$('#mOverdue').textContent=s.overdueServiceOrders??0;if(selectedOccurrence){const n=occurrences.find(x=>x.id===selectedOccurrence.id);if(n)showOccurrence(n)}draw();}
async function api(url,body){const r=await authFetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||r.statusText);return j;}
$('#submitOccurrence').onclick=async()=>{try{els.formState.textContent='Registrando…';const j=await api('/v1/occurrences',{categoryCode:els.category.value,description:els.description.value,latitude:Number(els.lat.value),longitude:Number(els.lon.value),gpsAccuracyM:null,clientRequestId:crypto.randomUUID()});els.formState.textContent=`Protocolo ${j.occurrence.protocol} criado${j.duplicates?.length?' • possível duplicidade detectada':''}.`;els.description.value='';await refreshOperations();showOccurrence(j.occurrence);}catch(e){els.formState.textContent='Erro: '+e.message;}};
$('#locate').onclick=()=>{if(!navigator.geolocation){els.formState.textContent='Geolocalização indisponível neste navegador.';return;}els.formState.textContent='Obtendo localização…';navigator.geolocation.getCurrentPosition(p=>{els.lat.value=p.coords.latitude.toFixed(7);els.lon.value=p.coords.longitude.toFixed(7);els.formState.textContent=`GPS capturado • precisão aproximada ${Math.round(p.coords.accuracy)} m`;},e=>els.formState.textContent='GPS não autorizado/disponível: '+e.message,{enableHighAccuracy:true,timeout:10000});};
$('#pick').onclick=()=>{pickMode=true;els.pickBanner.classList.remove('hidden');};
async function triage(id,decision){try{let duplicateOf=null;if(decision==='DUPLICATE'){const cand=occurrences.find(x=>x.id!==id&&x.categoryCode===selectedOccurrence.categoryCode);if(!cand){els.formState.textContent='Não existe outra ocorrência da mesma categoria para vincular como duplicada.';return;}duplicateOf=cand.id;}await api(`/v1/occurrences/${id}/triage`,{decision,duplicateOf});await refreshOperations();}catch(e){els.formState.textContent='Triagem: '+e.message;}}
async function advance(id,status){try{await api(`/v1/work-orders/${id}/status`,{status});await refreshOperations();}catch(e){els.formState.textContent='Ordem de serviço: '+e.message;}}
function connectWs(){const ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws/occurrences?access_token=${encodeURIComponent(accessToken)}`);ws.onopen=()=>{els.wsState.textContent='TEMPO REAL • ONLINE';els.wsState.className='badge';};ws.onmessage=async()=>{await refreshOperations();};ws.onclose=()=>{els.wsState.textContent='TEMPO REAL • RECONECTANDO';els.wsState.className='badge warning';setTimeout(connectWs,1200);};ws.onerror=()=>{els.wsState.textContent='TEMPO REAL • OFFLINE';els.wsState.className='badge offline';};}
for(const el of [els.zone,els.bairro])el.addEventListener('change',fit);els.mode.addEventListener('change',draw);$('#fit').addEventListener('click',fit);new ResizeObserver(draw).observe(canvas);fit();if(accessToken){try{const r=await authFetch('/v1/auth/me');if(r.ok){currentUser=await r.json();els.authState.textContent=`${currentUser.displayName} • ${currentUser.roles.join(', ')}`;await refreshOperations();connectWs();}}catch{}}

document.querySelectorAll('[data-report]').forEach(b=>b.onclick=async()=>{if(!accessToken)return alert('Entre na Central.');const r=await authFetch(`/v1/reports/occurrences.${b.dataset.report}`);if(!r.ok){const j=await r.json();return alert(j.error||r.statusText)}const blob=await r.blob(),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`urbis-occurrences.${b.dataset.report}`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);});
