import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import path from 'node:path';
import { DatabaseService } from '../database/database.service';
import { ObjectStorageService } from '../storage/object-storage.service';
import { RealtimeService } from '../realtime/realtime.service';
import { assessICI } from './evidence-scoring';
const TYPES:{[k:string]:string}={'image/jpeg':'.jpg','image/png':'.png','image/webp':'.webp','video/mp4':'.mp4'};
function decode(v:unknown){const s=String(v??'').replace(/^data:[^;]+;base64,/i,'').replace(/\s+/g,'');if(!s)throw new BadRequestException('dataBase64 obrigatório');const b=Buffer.from(s,'base64');if(!b.length)throw new BadRequestException('evidência vazia');if(b.length>8*1024*1024)throw new BadRequestException('evidência excede 8 MB');return b;}
function privileged(roles:string[]){return roles.some(r=>['OPERATOR','MANAGER','ADMIN'].includes(r));}
function isField(roles:string[]){return roles.includes('FIELD_AGENT');}
@Injectable()
export class EvidenceService {
  constructor(private readonly db:DatabaseService,private readonly storage:ObjectStorageService,private readonly realtime:RealtimeService){}
  private async assignedField(user:any,occurrenceId:string){if(!isField((user.roles??[]).map((x:string)=>String(x).toUpperCase())))return false;const q=await this.db.query(`SELECT 1 FROM work_orders w JOIN team_members tm ON tm.team_id=w.team_id AND tm.active=true WHERE w.occurrence_id=$1 AND tm.user_id=$2 LIMIT 1`,[occurrenceId,user.sub]);return Boolean(q.rowCount);}
  private async canAccess(user:any,o:any){const roles=(user.roles??[]).map((x:string)=>String(x).toUpperCase());return privileged(roles)||o.reporter_user_id===user.sub||await this.assignedField(user,o.id);}
  private async occurrence(id:string){const q=await this.db.query(`SELECT id,protocol,reporter_user_id,evidence_state,ici_score,ici_level,ici_algorithm,ST_Y(point) AS latitude,ST_X(point) AS longitude,created_at FROM occurrences WHERE id=$1`,[id]);if(!q.rowCount)throw new NotFoundException('ocorrência não encontrada');return q.rows[0] as any;}
  async list(id:string,user:any){const o=await this.occurrence(id);if(!await this.canAccess(user,o))throw new ForbiddenException();const q=await this.db.query(`SELECT id,occurrence_id,object_key,media_type,original_filename,byte_length,sha256,hash_verified,captured_at,ST_Y(point) latitude,ST_X(point) longitude,authority_validated,validated_by,validated_at,storage_driver,metadata,created_at FROM occurrence_media WHERE occurrence_id=$1 ORDER BY created_at`,[id]);return {count:q.rowCount??0,records:q.rows};}
  async upload(id:string,body:Record<string,unknown>,user:any){
    const o=await this.occurrence(id);if(!await this.canAccess(user,o))throw new ForbiddenException();const mediaType=String(body.mediaType??'').toLowerCase(),ext=TYPES[mediaType];if(!ext)throw new BadRequestException('mediaType não suportado');const buffer=decode(body.dataBase64);const stored=await this.storage.putContentAddressed(buffer,mediaType,ext);const lat=body.latitude==null?null:Number(body.latitude),lon=body.longitude==null?null:Number(body.longitude);if((lat!=null&&!Number.isFinite(lat))||(lon!=null&&!Number.isFinite(lon)))throw new BadRequestException('coordenadas da evidência inválidas');
    const purpose=['REPORT','BEFORE','AFTER','FIELD'].includes(String(body.purpose??'REPORT').toUpperCase())?String(body.purpose??'REPORT').toUpperCase():'REPORT';const media=await this.db.tx(async c=>{const m=await c.query(`INSERT INTO occurrence_media(occurrence_id,object_key,media_type,sha256,captured_at,point,metadata,original_filename,byte_length,hash_verified,storage_driver,uploaded_by) VALUES($1,$2,$3,$4,$5,CASE WHEN $6::float8 IS NULL OR $7::float8 IS NULL THEN NULL ELSE ST_SetSRID(ST_MakePoint($7,$6),4326) END,$8,$9,$10,true,$11,$12) RETURNING id,occurrence_id,object_key,media_type,sha256,captured_at,original_filename,byte_length,hash_verified,storage_driver,created_at`,[id,stored.objectKey,mediaType,stored.sha256,body.capturedAt??null,lat,lon,JSON.stringify({source:'URBIS_API',integrity:'sha256',purpose}),path.basename(String(body.filename??`evidence${ext}`)).slice(0,120),stored.byteLength,stored.driver,user.sub]);const dup=await c.query(`SELECT count(*)::int AS n FROM occurrence_duplicate_candidates WHERE occurrence_id=$1`,[id]);const evidence={...m.rows[0],latitude:lat,longitude:lon,mediaType,byteLength:stored.byteLength,hashVerified:true,capturedAt:body.capturedAt??null,authorityValidated:false};const ici=assessICI({occurrence:{latitude:Number(o.latitude),longitude:Number(o.longitude),createdAt:o.created_at},evidence,user:{roles:user.roles},corroborationCount:dup.rows[0]?.n??0,authorityValidated:false});await c.query(`INSERT INTO occurrence_evidence_assessments(occurrence_id,media_id,algorithm_version,score,level,weights,factors,details,interpretation,assessed_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[id,m.rows[0].id,ici.algorithm,ici.score,ici.level,JSON.stringify(ici.weights),JSON.stringify(ici.factors),JSON.stringify(ici.details),ici.interpretation,user.sub]);await c.query(`UPDATE occurrences SET evidence_state='EVIDENCE_VALIDATED',ici_score=$2,ici_level=$3,ici_algorithm=$4,updated_at=now() WHERE id=$1`,[id,ici.score,ici.level,ici.algorithm]);await c.query(`INSERT INTO realtime_outbox(topic,entity_type,entity_id,payload) VALUES('evidence.created','evidence',$1,$2)`,[m.rows[0].id,JSON.stringify({occurrenceId:id,ici})]);return {...m.rows[0],latitude:lat,longitude:lon,ici};});this.realtime.publish({topic:'evidence.created',entityType:'evidence',entityId:String(media.id),payload:{occurrenceId:id,ici:media.ici}});return {evidence:media,occurrence:{id,protocol:o.protocol,evidenceState:'EVIDENCE_VALIDATED',ici:media.ici}};
  }
  async validateAuthority(id:string,mediaId:string,user:any){if(!privileged((user.roles??[]).map((x:string)=>String(x).toUpperCase())))throw new ForbiddenException();const o=await this.occurrence(id);const q=await this.db.query(`SELECT id,occurrence_id,media_type,byte_length,hash_verified,captured_at,ST_Y(point) latitude,ST_X(point) longitude FROM occurrence_media WHERE id=$1 AND occurrence_id=$2`,[mediaId,id]);if(!q.rowCount)throw new NotFoundException('evidência não encontrada');const m:any=q.rows[0];const dup=await this.db.query(`SELECT count(*)::int AS n FROM occurrence_duplicate_candidates WHERE occurrence_id=$1`,[id]);const ici=assessICI({occurrence:{latitude:Number(o.latitude),longitude:Number(o.longitude),createdAt:o.created_at},evidence:{mediaType:m.media_type,byteLength:m.byte_length,hashVerified:m.hash_verified,capturedAt:m.captured_at,latitude:m.latitude,longitude:m.longitude},user:{roles:user.roles},corroborationCount:dup.rows[0]?.n??0,authorityValidated:true});await this.db.tx(async c=>{await c.query(`UPDATE occurrence_media SET authority_validated=true,validated_by=$3,validated_at=now() WHERE id=$1 AND occurrence_id=$2`,[mediaId,id,user.sub]);await c.query(`INSERT INTO occurrence_evidence_assessments(occurrence_id,media_id,algorithm_version,score,level,weights,factors,details,interpretation,assessed_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[id,mediaId,ici.algorithm,ici.score,ici.level,JSON.stringify(ici.weights),JSON.stringify(ici.factors),JSON.stringify(ici.details),ici.interpretation,user.sub]);await c.query(`UPDATE occurrences SET evidence_state='AUTHORITY_VALIDATED',ici_score=$2,ici_level=$3,ici_algorithm=$4,updated_at=now() WHERE id=$1`,[id,ici.score,ici.level,ici.algorithm]);});this.realtime.publish({topic:'evidence.authority_validated',entityType:'evidence',entityId:mediaId,payload:{occurrenceId:id,ici}});return {occurrenceId:id,evidenceId:mediaId,evidenceState:'AUTHORITY_VALIDATED',ici};}
  async ici(id:string,user:any){const o=await this.occurrence(id);if(!await this.canAccess(user,o))throw new ForbiddenException();const q=await this.db.query(`SELECT algorithm_version,score,level,weights,factors,details,interpretation,created_at FROM occurrence_evidence_assessments WHERE occurrence_id=$1 ORDER BY created_at DESC LIMIT 1`,[id]);return {occurrenceId:id,protocol:o.protocol,evidenceState:o.evidence_state,ici:q.rows[0]??null,notice:'ICI-URBIS é indicador de confiança de engenharia e não prova automática de veracidade ou autenticidade.'};}
}
